---
title: "Analysis of Ecosystems homework week 4"
subtitle: "Distributions"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: "Put your name here"
output:
  word_document: default
---

```{r setup, echo=FALSE, message = FALSE, results='hide'}
knitr::opts_chunk$set(message = FALSE, warning=FALSE, 
                      echo=FALSE, results='hide')
if (!require("pacman")) install.packages("pacman")
pacman::p_load(s20x, plyr, ggplot2)
```

# Data preparation 

```{r chunk3, echo=FALSE, results='verbatim'}
mpg$origin <- as.factor(plyr::revalue(mpg$manufacturer, 
                                c("audi"="Foreign","chevrolet"="USA",
                                  "dodge"="USA", "ford"="USA","jeep"="USA", 
                                  "honda"="Foreign", "hyundai"="Foreign",
                                  "land rover"="Foreign","subaru"="Foreign", 
                                  "lincoln"="USA", "mercury"="USA", 
                                  "nissan"="Foreign", "pontiac"="USA", 
                                  "toyota"="Foreign","volkswagen"="Foreign"))) 
str(mpg)
```

# Continous data 

## Distribution 

### Make a graph

```{r chunk4, echo=TRUE, results='verbatim'}
# Insert ggplot script  
```

### Interpret the graph



## Probability Density Function

### Add PDF curve to the graph

```{r chunk5, echo=TRUE, results='verbatim'}
# Code Chunk 5: Insert ggplot script  

```

### Interpret the graph


## Graph a different continuous distribution 

### Transformation graph

```{r chunk6, echo=TRUE, results='verbatim'}
# Insert ggplot script for transformed data 

```

### Interpretation 



# Discrete data

## Distribution 

```{r chunk7, echo=FALSE, results='verbatim'}

class.ct <- count(mpg, vars="class") # New d.f. of counts/group
colnames(class.ct)[[2]] <- "count"
class.ct$freq <- round(with(class.ct, # create a frequency column
                            count/sum(count)), 3) 
class.ct <- class.ct[with(class.ct, order(-freq)), ] # Re-order by freq
str(class.ct)

```

### Make a graph

```{r chunk8, echo=TRUE, results='verbatim'}
# Insert ggplot script
## Here's a hint: in the ggplot call, make x=reorder(class, -freq, max)
## This will plot your bars in the correct order (largest on the left)

```

### Add PMF

```{r chunk9, echo=TRUE, results='verbatim'}
# Insert ggplot script

```

### Interpret the graph


